source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Example' do

  pod 'Yoga', path: '../../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../../node_modules/react-native/React.podspec'
  pod 'react-native-amap3d', path: '../../'

end
