platform :ios, '8.0'

target 'RNAMap3D' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/'
  pod 'react-native-amap3d', path: '../../'
end
