platform :ios, '8.0'

target 'RNAMap3D' do
  pod 'React', path: '../node_modules/react-native/'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/', :subspecs => [
    'DevSupport',
  ]
  pod 'react-native-amap3d', path: '../lib/ios/'
end
